"""
Módulo de configurações do projeto.
"""
from .settings import (
    PROJECT_ROOT,
    OPENSEARCH_HOST,
    OPENSEARCH_PORT,
    OPENSEARCH_USER,
    OPENSEARCH_PASSWORD,
    OPENSEARCH_USE_SSL,
    OPENAI_API_KEY,
    OPENAI_MODEL,
    OPENAI_EMBEDDING,
    ANTHROPIC_API_KEY,
    DATA_DIR,
    RAW_DATA_DIR,
    JSON_EXTRACTED_CONTENT,
    EVAL_DATA_DIR,
    METADATA_INDEX,
    CONTENT_INDEX,
    TAGS_IGNORADAS,
)
from .logger import setup_logger

__all__ = [
    "PROJECT_ROOT",
    "OPENSEARCH_HOST",
    "OPENSEARCH_PORT",
    "OPENSEARCH_USER",
    "OPENSEARCH_PASSWORD",
    "OPENSEARCH_USE_SSL",
    "OPENAI_API_KEY",
    "OPENAI_MODEL",
    "OPENAI_EMBEDDING",
    "ANTHROPIC_API_KEY",
    "DATA_DIR",
    "RAW_DATA_DIR",
    "JSON_EXTRACTED_CONTENT",
    "EVAL_DATA_DIR",
    "METADATA_INDEX",
    "CONTENT_INDEX",
    "TAGS_IGNORADAS",
    "setup_logger",
]
